version: '3.9'

services:
  db:
    container_name: motordb

    image: mysql

    command: --default-authentication-plugin=mysql_native_password
    
    restart: always

    ports: 
      - '3306:3306'

    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=motordb
      - MYSQL_USER=motordb
      - MYSQL_PASSWORD=motordb

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h","localhost", "-u", "root", "-proot"]
      interval: 15s
      timeout: 120s
      retries: 10

    volumes:
      - db_vol:/usr/app/mysql
    #network_mode: "host"

  app:
    container_name: motorapp
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      db:
        condition: service_healthy
    #entrypoint: ["/bin/bash", "-c", "npx", "run", "sequelize-cli", "db:migrate"]
    #network_mode: "host"

volumes:
  db_vol: