version: '3.9'

services:
  db:
    container_name: MotorDB
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_docker
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h","localhost", "-u", "root", "-proot"]
      interval: 15s
      timeout: 120s
      retries: 10
    volumes:
      - db_vol:/usr/app/mysql

  app:
    container_name: Motorapp
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_vol: